### PR TITLE
Fix public headers inclusion (+ small other fixes)

### LINKED ISSUE #564: Do not expose mustache (and other depedency/tools) in public headers.
The public header otherTools.h include mustache.h (https://github.com/kiwix/libkiwix/blob/master/include/tools/otherTools.h#L27).
By doing thing, we defacto make mustache a direct dependency of projects using libkiwix.
If somehow `otherTools.h` is include by a project foo. The mustache header must be present even if foo never use mustache.
This is what happen here https://github.com/kiwix/kiwix-desktop/runs/2904840393?check_suite_focus=true (PR https://github.com/kiwix/kiwix-desktop/pull/656) where the compilation of kiwix-desktop fails as mustache.hpp is not present.

We must not include header of our private dependencies in public our headers.

More than just cleaning the mustache inclusion (and other tools, we also include `zim.h` and we should not), we should probably carrefully select what helper function are part of our API and move all other tools private.

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #564

This also fix some declaration of `SuggestionItem` methods.

~~On recent gcc, httplib raise warning and it break compilation with `-WError`.
This PR include a patch for this. Upstream patch is here : https://github.com/yhirose/cpp-httplib/pull/980~~
This has been removed from the PR as it fix a issue I've got only on my computer and the fix make macos compilation fail.

### CODE REVIEW

File: include/tools.h [hunk 1]
```diff
@@ -20,4 +20,144 @@
...
+ * real executable is different of the path of the archive.
+ * If `realPathOnly` is true, return the path of the real executable instead of the
+ * archive launched by the user.
+ *
+ * @param realPathOnly If we must return the real path of the executable.
+ * @return the path of the executable (utf8 encoded)
+ */
+std::string getExecutablePath(bool realPathOnly = false);
+
+/** Tell if the pat is a relative path.
```
Comment (veloman-yunkan) [inline include/tools.h:67]: pat → path

File: include/tools.h [hunk 2]
```diff
@@ -20,4 +20,144 @@
...
+ *
+ * This function is provided as a small helper. It is probably better to use native tools
+ * to manipulate pathes.
```
Comment (veloman-yunkan) [inline include/tools.h:70]: pathes → paths

File: include/tools.h [hunk 3]
```diff
@@ -20,4 +20,144 @@
...
+/** Append a path to another one.
+ *
+ * This function is provided as a small helper. It is probably better to use native tools
+ * to manipulate pathes.
+ *
+ * @param basePath the base path.
+ * @param relativePath a path to add to the base path, must be a relative path.
+ * @return The concatenation of the pathes, using the right separator.
+ */
+std::string appendToDirectory(const std::string& directoryPath, const std::string& filename);
```
Comment (veloman-yunkan) [inline include/tools.h:86]: mismatch between the param names in the docstring and the function declaration

File: include/tools.h [hunk 4]
```diff
@@ -20,4 +20,144 @@
...
+
+/** Remove the last element of a path.
+ *
+ * This function is provided as a small helper. It is probably better to use native tools
+ * to manipulate pathes.
+ *
+ * @param path a path.
+ * @return The parent directory (or empty string is none).
```
Comment (veloman-yunkan) [inline include/tools.h:94]: is → if

File: include/tools.h [hunk 5]
```diff
@@ -20,4 +20,144 @@
...
+
+/** Remove the last element of a path.
+ *
+ * This function is provided as a small helper. It is probably better to use native tools
+ * to manipulate pathes.
+ *
+ * @param path a path.
+ * @return The base name of the path or empty string is none (ending with a separator).
+ */
+std::string getLastPathElement(const std::string& path);
```
Comment (veloman-yunkan) [inline include/tools.h:106]: 1. Mismatch between the function name and the first line of the docstring (a copy-paste error).
2. is → if (in the last line)

File: include/tools.h [hunk 6]
```diff
@@ -20,4 +20,144 @@
...
+ *
+ * This function is provided as a small helper. It is probably better to use native tools.
+ *
+ * @param str The string to split.
+ * @param delims A string of potential delimiters.
+ * @param trimEmpty true if empty part must be trimmed from the result.
+ * @param keepDelim true if delimiter must be included from the result.
+ * @return a list of part (potentially containing delimiters)
+ */
+std::vector<std::string> split(const std::string& str, const std::string& delims, bool trimEmpty=true, bool keepDelim = false);
```
Comment (veloman-yunkan) [inline include/tools.h:150]: 1. The effect of `trimEmpty` is not clear (probably because the term *trim* has a slightly different meaning in text processing related utilities). Maybe, renaming this parameter to `dropEmpty` will eliminate the confusion
2. Regarding `keepDelim` - where exactly in (rather than from) the result is the delimiter included

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: include/tools.h (hunk 2 above)
Comment (maneeshpm) [reply include/tools.h:70]: Please note that this typo is present in other function docstrings as well.

Comment (mgautierfr) [reply include/tools.h:70]: I don't know why my brain keep thinking that paths is written pathes. Even if **I** know it is not the case.

File: include/tools.h (hunk 6 above)
Comment (mgautierfr) [reply include/tools.h]: Done.
I've also add a small example.

File: include/tools.h [hunk 7]
```diff
@@ -141,6 +141,13 @@ void sleep(unsigned int milliseconds);
  *
  * This function is provided as a small helper. It is probably better to use native tools.
  *
+ * Assuming text = "foo:;bar;baz,oups;"
+ *
+ * slit(text, ":;", true, true) => ["foo", ":", ";", "bar", ";", "baz,oups", ";"]
```
Comment (maneeshpm) [inline include/tools.h:146]: A minor typo.

File: include/tools.h [hunk 8]
```diff
@@ -150,11 +150,11 @@ void sleep(unsigned int milliseconds);
  *
  * @param str The string to split.
  * @param delims A string of potential delimiters.
- * @param trimEmpty true if empty part must be trimmed from the result.
+ * @param dropEmpty true if empty part must be dropped from the result.
  * @param keepDelim true if delimiter must be included from the result.
  * @return a list of part (potentially containing delimiters)
  */
-std::vector<std::string> split(const std::string& str, const std::string& delims, bool trimEmpty=true, bool keepDelim = false);
+std::vector<std::string> split(const std::string& str, const std::string& delims, bool dropEmpty=true, bool keepDelim = false);
```
Comment (maneeshpm) [inline include/tools.h:157]: The example suggests that each character of the string `delims` is a potential delimiter. It can be easily confused with the entire string being a single delimiter. I think we should mention this explicitly in the parameter docstring.

**Review by maneeshpm — CHANGES_REQUESTED** [review]
Just a couple of comments for better docstring

**Comment by mgautierfr** [comment]
Rebase on master (fixing the conflict (new archiveTools.h)).

Fix last review comments of @maneeshpm

**Review by maneeshpm — APPROVED** [review]

**Comment by kelson42** [comment]
This branch needs to be rebased

**Comment by kelson42** [comment]
IMO we can merge now.
