### PR TITLE
Small search improvement.

### LINKED ISSUE #723: Wrong html entities in kiwix-serve ft result page
Look:
image

Which should properly see the search pattern with "<toto>"

### PR DESCRIPTION
**Pull request by mgautierfr**
This PR fixes small issues found on search handling on the server.
It is somehow a preparatory work for openSearch feature coming soon.

Fixes #723

### CODE REVIEW

File: src/server/internalServer.cpp [hunk 1]
```diff
@@ -513,8 +513,11 @@ std::unique_ptr<Response> InternalServer::handle_search(const RequestContext& re
   } catch (const std::out_of_range&) {}
 
   /* Make the search */
-  if ( (!archive && !bookName.empty())
-    || (patternString.empty() && ! has_geo_query) ) {
+  if (patternString.empty() && ! has_geo_query) {
+    return Response::build_400(*this, "No query provided.");
```
Comment (veloman-yunkan) [inline src/server/internalServer.cpp]: Here `"No query provided."` serves as the `url` parameter

File: test/server.cpp [hunk 2]
```diff
@@ -322,6 +321,19 @@ TEST_F(ServerTest, 404)
...
+  "/ROOT/search",
+  "/ROOT/search?content=zimfile",
+  "/ROOT/search?pattern",
+};
+
+
+TEST_F(ServerTest, 400)
+{
+  for (const char* url: urls400 )
+    EXPECT_EQ(400, zfs1_->GET(url)->status) << "url: " << url;
```
Comment (veloman-yunkan) [inline test/server.cpp:334]: Please add braces to the body of the loop

File: src/server/internalServer.cpp [hunk 3]
```diff
@@ -109,6 +109,66 @@ unsigned int getCacheLength(const char* name, unsigned int defaultVal) {
...
+    query.setGeorange(geo_query.latitude, geo_query.longitude, geo_query.distance);
+  } else {
+    // Execute Ft search
+    if (verbose) {
+        cout << "Performing query `" << pattern << "'" << endl;
+    }
+    query.setQuery(pattern);
+  }
+  return query;
+}
```
Comment (veloman-yunkan) [inline src/server/internalServer.cpp:169]: Such an implementation of `SearchInfo::getZimQuery()` makes the `SearchInfo::SearchInfo(const std::string& pattern, GeoQuery geo_query)` constructor meaningless

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
The second commit (the one titled "Introduce SearchInfo.") is a little two big and a little too different to validate. It will benefit from being split into smaller changes.

File: src/server/internalServer.cpp (hunk 1 above)
Comment (mgautierfr) [reply src/server/internalServer.cpp]: I've split the change in several commit and miss this.

This is fixed, directly in the new commit.

File: test/server.cpp (hunk 2 above)
Comment (mgautierfr) [reply test/server.cpp:334]: Done in a new commit (which add braces around several for loops)

File: src/server/internalServer.cpp (hunk 3 above)
Comment (mgautierfr) [reply src/server/internalServer.cpp:169]: This is what was done previously. But yes, it is better to always use the pattern if provided.
Changed in a new commit.

**Comment by kelson42** [comment]
@mgautierfr Can we move one please with this PR?

**Comment by veloman-yunkan** [comment]
> @mgautierfr Can we move one please with this PR?

@kelson42 I would like to bring to your attention the situation with this PR described in https://github.com/kiwix/libkiwix/pull/727#issuecomment-1072369936. If we postpone this PR until the preparatory work for internationalizing kiwix-serve is completed, then it can be rewritten in a slightly cleaner way (while at the same time minimizing the need for addressing conflicts in a larger WIP PR #679).

**Comment by kelson42** [comment]
@veloman-yunkan Not against the principle, but concerned about the overall timelime and interdependences. Considering that we have an XSS issue in the field with kiwix-serve... I would like to consider a minor release within the next 2-3 weeks.

**Comment by mgautierfr** [comment]
The "problem" is that this PR is somehow a preparatory work for other PRs introducing opensearch feature.
And I'm affraid #679 will not be merged soon. But we will have merge conflicts and we must minimize them. I can rebase this PR on #727 easyily. 
@veloman-yunkan will it be enough ? If not, can you extract another preparatory PR from #679 (And rebase this PR on your newly created PR) ?

**Comment by mgautierfr** [comment]
Rebased on last master (with #727 merged)

**Comment by veloman-yunkan** [comment]
> > If not, can you extract another preparatory PR from #679 (And rebase this PR on your newly created PR) ?
> 
> I will do it tomorrow.

The new PR extracted from #679 is #732. Unfortunately, a few changes that I intended to include in #732 were too tightly coupled with internationalization of kiwix-serve so I left them for another smaller follow-up PR.

**Comment by kelson42** [comment]
@mgautierfr I guess this is now ready to fix/merge.

**Comment by mgautierfr** [comment]
Rebased on master (with #732 merged)

File: src/server/internalServer.h [hunk 4]
```diff
@@ -43,9 +43,47 @@ extern "C" {
...
+    friend bool operator<(const SearchInfo& l, const SearchInfo& r)
+    {
+        return std::tie(l.bookName, l.pattern, l.has_geo_query, l.geo_query)
+             < std::tie(r.bookName, r.pattern, r.has_geo_query, r.geo_query); // keep the same order
+    }
+
+  public: //data
+    std::string pattern;
+    bool has_geo_query;
+    GeoQuery geo_query;
```
Comment (veloman-yunkan) [inline src/server/internalServer.h:79]: A camel would feel like its rights are neglected here :)

**Review by veloman-yunkan — APPROVED** [review]
LGTM. But I am also including couple of optional suggestions for minor improvements that could be made while moving the code around.

File: src/server/internalServer.cpp [hunk 5]
```diff
@@ -109,6 +109,66 @@ unsigned int getCacheLength(const char* name, unsigned int defaultVal) {
...
+{}
+
+SearchInfo::SearchInfo(const RequestContext& request)
+  : pattern(""),
+    has_geo_query(false),
+    geo_query(0, 0, 0)
+{
+  try {
+    pattern = request.get_argument("pattern");
+  } catch (const std::out_of_range&) {}
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply src/server/internalServer.cpp:131]: Yes, I've seen you add this method but forget to use it in the rebase.

While I'm here, I realize the methods `get_optional_param` and `get_argument`. Why param and not argument ? Should we have the same term for consistency ?

**Comment by mgautierfr** [comment]
I've fixed your comment in two fixup commits

File: src/server/internalServer.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply src/server/internalServer.cpp]: In my choice of the name for the new method I followed the conventional terminology (see https://stackoverflow.com/questions/156767/whats-the-difference-between-an-argument-and-a-parameter). `get_argument()` doesn't contradict it, but `get_optional_argument()` would sound somewhat nonsensical.

File: src/server/internalServer.h [hunk 6]
```diff
@@ -62,21 +62,20 @@ struct GeoQuery {
...
-             < std::tie(r.bookName, r.pattern, r.has_geo_query, r.geo_query); // keep the same order
+        return std::tie(l.bookName, l.pattern, l.geoQuery)
+             < std::tie(r.bookName, r.pattern, r.geoQuery); // keep the same order
     }
 
   public: //data
     std::string pattern;
-    bool has_geo_query;
-    GeoQuery geo_query;
+    std::pair<bool, GeoQuery> geoQuery;
```
Comment (veloman-yunkan) [inline src/server/internalServer.h:78]: I don't like this. A better solution is to take advantage of the fact that `GeoQuery` can have an invalid state (for example when `distance < 0`) without adding a new data field to it. Add a proper default constructor to `GeoQuery` and a `bool isValid() const` member function.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/server/internalServer.h (hunk 6 above)
Comment (mgautierfr) [reply src/server/internalServer.h]: Done with a `operator bool` operator

File: src/server/internalServer.h [hunk 7]
```diff
@@ -44,13 +44,20 @@ extern "C" {
...
+  {}
+
   GeoQuery(float latitude, float longitude, float distance)
     : latitude(latitude), longitude(longitude), distance(distance)
   {}
   float latitude;
   float longitude;
   float distance;
 
+  operator bool() const {
```
Comment (veloman-yunkan) [inline src/server/internalServer.h:58]: We don't have that risk now, but for safety such conversion must be declared `explicit`.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/server/internalServer.h (hunk 7 above)
Comment (mgautierfr) [reply src/server/internalServer.h]: Done

**Review by veloman-yunkan — APPROVED** [review]
