### PR TITLE
Make OPDSDumper respect the NameMapper of the server.

### LINKED ISSUE #828: OPDS catalog must respect the used nameMapper
**Describe the bug**
On libkiwix 10.1.1 , zim file while opening over hotspot resulting ```The requested URL "/" was not found on this server.```.

**Expected behavior**
Its should open the zim file without any issue

**Screenshots**
Screenshot from 2022-10-03 18-52-57
Screenshot from 2022-10-03 18-53-01

**Environment**
- Version of Kiwix Android : 3.7.0
- Device : REDMI NOTE 9
- OS version : 11

### PR DESCRIPTION
**Pull request by mgautierfr**
It is an extract of #830 which become a bit too big because of associated refactoring.
This PR concentrate on fixing #828

Fixes #828

### CODE REVIEW

File: src/opds_dumper.cpp [hunk 1]
```diff
@@ -71,7 +72,7 @@ IllustrationInfo getBookIllustrationInfo(const Book& book)
     return illustrations;
 }
 
-std::string fullEntryXML(const Book& book, const std::string& rootLocation)
+std::string fullEntryXML(const Book& book, const std::string& rootLocation, const std::string& bookName)
```
Comment (veloman-yunkan) [inline src/opds_dumper.cpp:75]: We get back to https://github.com/kiwix/libkiwix/pull/830#discussion_r990609558:

> `bookName` is not a good name for this new parameter (taking into account the line `{"name", book.getName()},` below.

The easiest solution for this small PR is to pass into this function the `NameMapper` object instead.

File: test/library_server.cpp [hunk 2]
```diff
@@ -774,4 +783,42 @@ TEST_F(LibraryServerTest, catalog_search_excludes_hidden_tags)
 #undef EXPECT_ZERO_RESULTS
 }
 
+#define NO_MAPPER_CHARLES_RAY_CATALOG_ENTRY _CHARLES_RAY_CATALOG_ENTRY("charlesray")
+#define NO_MAPPER_RAY_CHARLES_CATALOG_ENTRY _RAY_CHARLES_CATALOG_ENTRY("raycharles")
```
Comment (veloman-yunkan) [inline test/library_server.cpp:787]: Isn't it better to have these defined immediately next to their name-mapped counterparts so that the difference is obvious?

File: test/server.cpp [hunk 3]
```diff
@@ -131,6 +131,13 @@ TEST_F(ServerTest, 200)
     EXPECT_EQ(200, zfs1_->GET(res.url)->status) << "res.url: " << res.url;
 }
 
+TEST_F(ServerTest, 200_IdNameMapper)
+{
+  resetServer(ZimFileServer::NO_NAME_MAPPER);
+  EXPECT_EQ(200, zfs1_->GET("/ROOT/content/6f1d19d0-633f-087b-fb55-7ac324ff9baf/A/index")->status);
+  EXPECT_EQ(404, zfs1_->GET("/ROOT/content/zimfile/A/index")->status);
```
Comment (veloman-yunkan) [inline test/server.cpp:138]: What do you think of having the 2 `EXPECT_EQ()` lines repeated before the `resetServer()` with their expected status codes swapped?

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/opds_dumper.cpp (hunk 1 above)
Comment (mgautierfr) [reply src/opds_dumper.cpp:75]: What about naming it `content_id` ?

File: test/server.cpp (hunk 3 above)
Comment (mgautierfr) [reply test/server.cpp:218]: Done

File: test/library_server.cpp [hunk 4]
```diff
@@ -115,6 +115,7 @@ std::string maskVariableOPDSFeedData(std::string s)
 )
 
 #define CHARLES_RAY_CATALOG_ENTRY _CHARLES_RAY_CATALOG_ENTRY("zimfile%26other")
+#define NO_MAPPER_CHARLES_RAY_CATALOG_ENTRY _CHARLES_RAY_CATALOG_ENTRY("charlesray")
```
Comment (veloman-yunkan) [inline test/library_server.cpp:118]: Proper alignment will help to emphasize the similarities and differences between these two lines. It would be even better if `NO_MAPPER_CHARLES_RAY_CATALOG_ENTRY` is renamed to `CHARLES_RAY_CATALOG_ENTRY_NO_MAPPER`. The same applies to `NO_MAPPER_RAY_CHARLES_CATALOG_ENTRY`

**Review by veloman-yunkan — COMMENTED** [review]
Please rebase & fixup. No need to go through another iteration if you decide to address the last minor comment.

File: test/library_server.cpp (hunk 4 above)
Comment (mgautierfr) [reply test/library_server.cpp]: Done

**Comment by kelson42** [comment]
@mgautierfr I think @veloman-yunkan has invited us to merge straight.

File: test/library_server.cpp (hunk 4 above)
Comment (veloman-yunkan) [reply test/library_server.cpp]: The suggestion to rename was meant to be *in addition* to the suggestion to align:

```c++
#define CHARLES_RAY_CATALOG_ENTRY           _CHARLES_RAY_CATALOG_ENTRY("zimfile%26other")
#define CHARLES_RAY_CATALOG_ENTRY_NO_MAPPER _CHARLES_RAY_CATALOG_ENTRY("charlesray")
```

**Review by veloman-yunkan — APPROVED** [review]
