### PR TITLE
Handling of external app links in the viewer

### LINKED ISSUE #1090: Relax the Content-Security-Policy to allow `mailto:` links in the Kiwix Serve iframe
This relates to issue https://github.com/kiwix/kiwix-tools/issues/680 on Kiwix Tools. Most links that are not considered secure are blocked by the CSP and/or sandbox, and that includes `mailto:` links, which are blocked in Chromium browsers (whereas they seem not be blocked by Firefox). This also affects Kiwix JS Browser Extension and the PWA.

I have determined (in the PWA) that relaxing the CSP ***for the content in the iframe*** should fix this. All that is needed is to add `mailto:` to the list of exceptions in the `internalServer.cpp` code. I am pretty sure it won't be necessary to alter the CSP of the outer document, but that would need testing. The code is here:

https://github.com/kiwix/libkiwix/blob/main/src/server/internalServer.cpp#L1110

A Zimit2 ZIM with a `maitlo:` link is given in the linked issue for testing.

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes kiwix/kiwix-tools#680 
Also closes #1090, but not as requested in the title & description of that issue because I couldn't make it work and chose the general approach proposed in an [afterthought](https://github.com/kiwix/libkiwix/issues/1090#issuecomment-2147755667) that was initially [posted](https://github.com/kiwix/kiwix-tools/issues/680#issuecomment-2147208056) in #680.

Links that should be handled/opened by external applications - such as email addresses (`mailto:`), phone numbers (`tel:`), etc - are opened by the viewer in a new tab/window, thus avoiding any issues with content security policy.

### CODE REVIEW

File: static/skin/viewer.js [hunk 1]
```diff
@@ -310,6 +310,17 @@ function blockLink(url) {
        : url;
 }
 
+function isExternalAppUrl(url) {
+  const EXTERNAL_APP_PROTOCOLS = ['mailto', 'tel', 'geo', 'magnet', 'zoomus'];
```
Comment (Jaifroid) [inline static/skin/viewer.js:314]: I personally wouldn't hardcode a list of URI schemata given that there are an infinite number of possible schemata, since webapps can define them arbitrarily. If we were only dealing with Wikimedia ZIMs, a hardcoded list might be appropriate, but for Zimit we could have literally any protocol, e.g. `skype:`, `bingmaps:`, `comgooglemaps:`, `comgooglemaps-x-callback:`, etc., etc., etc....? I think we need a different approach: have a list of URI schemata ("protocols") that we know can or must be opened in the app (I only found `javascript:` and `about:`), and open all the rest in a new tab or window.

**Review by Jaifroid — COMMENTED** [review]
As mentioned in comment, I'd suggest having a whitelist rather than a blacklist, because the blacklist could be infinite, whereas there are only a couple of protocols in the whitelist.

One thing to be aware of is that I found several cases of PDFs served with http:// protocols instead of https:// protocols in Zimit archives, so I had to include a normalizing step in the code in Kiwix JS here https://github.com/kiwix/kiwix-js/blob/main/www/js/app.js#L2451. Now, I don't know if that is only relevant for Zimit1, or if Zimit2 might have this issue or not. I don't know if you still want to support Zimit1 ZIMs that are likely to be around for quite some time? @benoit74?

**Comment by benoit74** [comment]
I have exactly the same remark / recommendation as @Jaifroid (who has been quicker than I to review this ^^)

In ZIMs, we can indeed have http:, https:, javascript:, about: (and maybe others, I don't really know tbh) that should be handled, all others should be just left for the browser to proceed. All these links should raised a warning from my PoV since the user is not navigating inside the ZIM but going somewhere else. When navigating inside the ZIM, only relative links are used normally.

Usage of http: and https: links are obviously way more common in Zimit than in other scrapers, but we can definitely have both in any (e.g. in ifixit we have many "external" links posted by users in the guides, and these could be http or https depending on what the target server supports or what the user decided to use ; and we do not try to guess if any http link could be replaced by an https one, this is too daunghting). Regarding links processed dynamically by wombat, when internal to the ZIM they use the same protocol as the currently displayed HTML page.

Regarding Zimit 1, currently openZIM does not have anymore Zimit 1 ZIMs published, they have all been either updated to Zimit 2 or archived. That been said, there is probably many in the wild, and we obviously have no control on when users will drop them for a more recent version.

**Comment by kelson42** [comment]
FYI and AFAIK there is such a list of protocol schemes in zimwriterfs source code as well.

**Comment by Jaifroid** [comment]
I think we'll need to test this thoroughly against any links transformed by Wombat. In @mgautierfr's original workaround, it was necessary to turn off Wombat processing temporarily when the user clicked a link in order to get the "real" URL as opposed to the Wombat-transformed URL. It's not clear to me whether that is relevant to this PR (sorry, I'm still travelling, so don't have access to a test environment right now).

File: static/skin/viewer.js (hunk 1 above)
Comment (veloman-yunkan) [reply static/skin/viewer.js]: Addressed in a fixup commit

**Comment by veloman-yunkan** [comment]
> All these links should raised a warning from my PoV since the user is not navigating inside the ZIM but going somewhere else.

Should this be implemented in this PR?

**Comment by benoit74** [comment]
> Should this be implemented in this PR?
No clue ^^

**Comment by kelson42** [comment]
> > All these links should raised a warning from my PoV since the user is not navigating inside the ZIM but going somewhere else.
> 
> Should this be implemented in this PR?

`-b --blockexternal` should apply to all external URLs if activated, otherwise I see no reason why we should display a warning. This is at least not the behaviour which has been chosen so far.

**Comment by veloman-yunkan** [comment]
> > > All these links should raised a warning from my PoV since the user is not navigating inside the ZIM but going somewhere else.
> > 
> > 
> > Should this be implemented in this PR?
> 
> @veloman-yunkan `-b --blockexternal` should apply to all external URLs if activated, otherwise I see no reason why we should display a warning. This is at least not the behaviour which has been chosen so far. Does it apply?

Done. Any links containing a non-whitelisted URL schema are now considered external with respect to link blocking and routed through the link-blocker page. Otherwise such links are opened in a new window/tab.

Also discovered a bug related to handling of ctrl (or shift) clicked links for Zimit2 ZIMs and fixed it in a separate commit.

**Review by kelson42 — APPROVED** [review]
LGTM

**Comment by veloman-yunkan** [comment]
> LGTM

I think that the additional bugfix commit was not included in your review.
