### PR TITLE
Really enable Chromium to display PDFs in the viewer iframe

### LINKED ISSUE #916: PDF content blocked by Chrome
When opening a PDF in a ZIM in the kiwix-serve viewer, on Chrome, there is an unrecoverable error message. This looks like a regression.

Screenshot 2023-03-15 at 14 18 57

Go to https://dev.library.kiwix.org/viewer#lilote_fr_fo_2023-03/xay-va-%C3%A0-la-p%C3%AAche then click the _Lire l'histoire_ button.

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #916

The previous "fix" (merged PR #92 ) was buggy. It not only didn't work in Chromium v90, but in more recent versions too.

I verified that this fix works in Firefox (v111) and Chromium (v90):

- Attempts by the ZIM content to break out of the viewer iframe are blocked.
- PDFs are displayed in the viewer.

Also (unrelated to the bug being addressed) removed `moz-extension:` and `chrome-extension:` from list of valid sources in content security policy as they are not justified for `kiwix-serve` (as [noted](https://github.com/kiwix/libkiwix/pull/924#discussion_r1152134334) in @Jaifroid's review of #924)

### CODE REVIEW

**Review by mgautierfr — APPROVED** [review]
LGTM

**Review by rgaudin — APPROVED** [review]
LGTM as well but I didn't test. I can't compile libzim on my box (https://github.com/openzim/libzim/issues/778) and on an ubuntu one, it compiles but the test fails…

**Comment by kelson42** [comment]
Mandatory to me is the approval of @Jaifroid

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr macos CI fails!

**Comment by rgaudin** [comment]
> @veloman-yunkan @mgautierfr macos CI fails!

It's no one's fault. We install packages via brew and one of the package's dependency is python which can't be linked because it's already linked.

I believe passing `--overwrite` to the `brew install` command could fix it but it's unrelated to this PR

**Comment by kelson42** [comment]
Another issue/PR needs then probably to be open asap.

**Comment by Jaifroid** [comment]
Sorry, I'm still 7 hours behind CET, will review shortly.

File: src/server/internalServer.cpp [hunk 1]
```diff
@@ -1184,6 +1207,13 @@ std::unique_ptr<Response> InternalServer::handle_content(const RequestContext& r
     auto response = ItemResponse::build(*this, request, entry.getItem());
     response->set_etag_body(archiveUuid);
 
+    if ( !startsWith(entry.getItem().getMimetype(), "application/pdf") ) {
```
Comment (Jaifroid) [inline src/server/internalServer.cpp:1210]: Are we confident that all PDFs will have a set MIME type, and that it will always be `application/pdf` (and always lowercase)? What about `text/pdf` or `application/x-pdf`, which can be used? I'm thinking of Zimit archives, where we don't really control such things (for Gutenberg and mwOffliner, we can be sure of the MIME type, I think).

**Review by Jaifroid — APPROVED** [review]
Thanks, this looks good to me with one query about the PDF MIME type which may just be over-cautious. N.B. I can't test because I can't build this on my Windows machine. I'll happily test it thoroughly once it has been merged and is available in the dev server.

File: src/server/internalServer.cpp (hunk 1 above)
Comment (veloman-yunkan) [reply src/server/internalServer.cpp:1210]: I think @mgautierfr and/or @rgaudin can answer this question better than me

Comment (Jaifroid) [reply src/server/internalServer.cpp:1210]: That's convincing to me!

**Comment by mgautierfr** [comment]
Seems we are good. I'm merging.
